name: API

on:
  workflow_dispatch:
  pull_request:
    paths:
      - package.json
      - api/**
    branches:
      - main
  push:
    paths:
      - api/**
    branches:
      - main

jobs:
  test-api:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          node-version: 12

      - name: npm auth
        run: |
          npm config set @kashw2:registry https://npm.pkg.github.com/
          npm config set //npm.pkg.github.com/:_authToken=${{ secrets.NPM_PACKAGE_TOKEN }}
          npm config set registry https://registry.npmjs.org/

      - name: install globals
        run: npm install -g lerna

      - name: npm install
        run: |
          npm install
          lerna exec npm install --scope=@ffk/api

      - name: build api
        run: lerna run test --scope=@ffk/api
  build-api:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          node-version: 12

      - name: npm auth
        run: |
          npm config set @kashw2:registry https://npm.pkg.github.com/
          npm config set //npm.pkg.github.com/:_authToken=${{ secrets.NPM_PACKAGE_TOKEN }}
          npm config set registry https://registry.npmjs.org/

      - name: install globals
        run: npm install -g lerna

      - name: npm install
        run: |
          npm install
          lerna exec npm install --scope=@ffk/api

      - name: build api
        run: lerna run build:dev --scope=@ffk/api
  deploy-api:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          node-version: 12

      - name: npm auth
        run: |
          npm config set @kashw2:registry https://npm.pkg.github.com/
          npm config set //npm.pkg.github.com/:_authToken=${{ secrets.NPM_PACKAGE_TOKEN }}
          npm config set registry https://registry.npmjs.org/

      - name: install globals
        run: npm install -g lerna

      - name: npm install
        run: |
          npm install
          lerna exec npm install --scope=@ffk/api

      - name: build api
        run: lerna run build:dev --scope=@ffk/api

      - name: deploy
        uses: docker/login-action@v1
        with:
          registry: ffkcontainerregistry.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - run: |
          docker build -t ffkcontainerregistry.azurecr.io/api.faithfulknights.com:${{ github.sha }} -t ffkcontainerregistry.azurecr.io/api.faithfulknights.com:latest -f Dockerfile .
          docker push ffkcontainerregistry.azurecr.io/api.faithfulknights.com:${{ github.sha }}
          docker push ffkcontainerregistry.azurecr.io/api.faithfulknights.com:latest
        working-directory: api
