name: Build lib-util

on:
  workflow_dispatch:
  pull_request:
    paths:
      - package.json
      - libs/util/**
    branches:
      - master

jobs:
  build-lib-util:
    runs-on: ubuntu-latest
    steps:
      - name: setup node
        uses: actions/checkout@v2
        with:
          node-version: 12

      - name: npm auth
        run: |
          npm config set @kashw2:registry https://npm.pkg.github.com/
          npm config set //npm.pkg.github.com/:_authToken=${{ secrets.NPM_PACKAGE_TOKEN }}
          npm config set registry https://registry.npmjs.org/

      - name: install globals
        run: sudo npm install -g lerna

      - name: npm install
        run: |
          npm install
          lerna exec npm install --scope=@kashw2/lib-util

      - name: build
        run: lerna run build --scope=@kashw2/lib-util
