name: Onboarding

on:
  workflow_dispatch:
  pull_request:
    paths:
      - package.json
      - onboarding/**
    branches:
      - main
  push:
    paths:
      - onboarding/**
    branches:
      - main

jobs:
  build-onboarding:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          node-version: 12

      - name: npm auth
        run: |
          npm config set @kashw2:registry https://npm.pkg.github.com/
          npm config set //npm.pkg.github.com/:_authToken=${{ secrets.NPM_PACKAGE_TOKEN }}
          npm config set registry https://registry.npmjs.org/

      - name: install globals
        run: npm install -g lerna

      - name: npm install
        run: |
          npm install
          lerna exec npm install --scope=@ffk/onboarding

      - name: build onboarding
        run: lerna run build:dev --scope=@ffk/onboarding
  deploy-onboarding:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          node-version: 12

      - name: npm auth
        run: |
          npm config set @kashw2:registry https://npm.pkg.github.com/
          npm config set //npm.pkg.github.com/:_authToken=${{ secrets.NPM_PACKAGE_TOKEN }}
          npm config set registry https://registry.npmjs.org/

      - name: install globals
        run: npm install -g lerna

      - name: npm install
        run: |
          npm install
          lerna exec npm install --scope=@ffk/onboarding

      - name: build onboarding
        run: lerna run build --scope=@ffk/onboarding

      - name: deploy
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      - run: |
          docker build -t gcr.io/the-sandbox-311907/onboarding:${{ github.sha }} -t gcr.io/the-sandbox-311907/onboarding:latest -f Dockerfile .
          docker push gcr.io/the-sandbox-311907/onboarding:${{ github.sha }}
          docker push gcr.io/the-sandbox-311907/onboarding:latest
        working-directory: onboarding
