name: Build Panel

on:
  workflow_dispatch:
  pull_request:
    paths:
      - package.json
      - panel/**
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: setup node
        uses: actions/checkout@v2
        with:
          node-version: 12

      - name: npm auth
        run: |
          npm config set @kashw2:registry https://npm.pkg.github.com/
          npm config set //npm.pkg.github.com/:_authToken=${{ secrets.NPM_PACKAGE_TOKEN }}
          npm config set registry https://registry.npmjs.org/

      - name: install globals
        run: sudo npm install -g lerna @angular/cli

      - name: npm install
        run: npm install

      - name: lerna bootstrap
        run: lerna exec npm i

      - name: build lib-angular
        run: lerna run build --scope=@kashw2/lib-angular

      - name: build panel
        run: lerna run build --scope=@ffk/panel
