name: lib-server

on:
  workflow_dispatch:
  pull_request:
    paths:
      - package.json
      - libs/server/**
    branches:
      - main

jobs:
  build-lib-server:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          node-version: 12

      - name: npm auth
        run: |
          npm config set @kashw2:registry https://npm.pkg.github.com/
          npm config set //npm.pkg.github.com/:_authToken=${{ secrets.NPM_PACKAGE_TOKEN }}
          npm config set registry https://registry.npmjs.org/

      - name: install globals
        run:  npm install -g lerna

      - name: npm install
        run: |
          npm install
          lerna exec npm install --scope=@kashw2/lib-server

      - name: build
        run: lerna run build --scope=@kashw2/lib-server
