name: lib-ts

on:
  workflow_dispatch:
  pull_request:
    paths:
      - package.json
      - libs/typescript/**
    branches:
      - main

jobs:
  build-lib-ts:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: npm auth
        run: |
          npm config set @kashw2:registry https://npm.pkg.github.com/
          npm config set //npm.pkg.github.com/:_authToken=${{ secrets.NPM_PACKAGE_TOKEN }}
          npm config set registry https://registry.npmjs.org/

      - name: install globals
        run:  npm install -g lerna

      - name: npm install
        run: |
          npm install
          lerna exec npm install --scope=@kashw2/lib-ts

      - name: build
        run: lerna run build:dev --scope=@kashw2/lib-ts
