name: Panel

on:
  workflow_dispatch:
  pull_request:
    paths:
      - package.json
      - panel/**
    branches:
      - main
  push:
    paths:
      - panel/**
    branches:
      - main

jobs:
  build-panel:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: npm auth
        run: |
          npm config set @kashw2:registry https://npm.pkg.github.com/
          npm config set //npm.pkg.github.com/:_authToken=${{ secrets.NPM_PACKAGE_TOKEN }}
          npm config set registry https://registry.npmjs.org/

      - name: install globals
        run:  npm install -g lerna @angular/cli &> /dev/null

      - name: npm install
        run: |
          lerna exec npm install --scope=fleet-of-the-faithful-knights
          lerna exec npm install --scope=@ffk/panel

      - name: build panel
        run: lerna run build --scope=@ffk/panel
  deploy-panel:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: npm auth
        run: |
          npm config set @kashw2:registry https://npm.pkg.github.com/
          npm config set //npm.pkg.github.com/:_authToken=${{ secrets.NPM_PACKAGE_TOKEN }}
          npm config set registry https://registry.npmjs.org/

      - name: install globals
        run: npm install -g lerna @angular/cli &> /dev/null

      - name: npm install
        run: |
          lerna exec npm install --scope=fleet-of-the-faithful-knights
          lerna exec npm install --scope=@ffk/panel

      - name: build panel
        run: lerna run build:prod --scope=@ffk/panel
        working-directory: panel

      - name: deploy
        uses: docker/login-action@v1
        with:
          registry: ffkcontainerregistry.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - run: |
          docker build -t ffkcontainerregistry.azurecr.io/panel.faithfulknights.com:${{ github.sha }} -t ffkcontainerregistry.azurecr.io/panel.faithfulknights.com:latest -f Dockerfile .
          docker push ffkcontainerregistry.azurecr.io/panel.faithfulknights.com:${{ github.sha }}
          docker push ffkcontainerregistry.azurecr.io/panel.faithfulknights.com:latest
        working-directory: panel

